### PR TITLE
Fix various Python3 issues

### PR DESCRIPTION
**Pull request by vidartf**
and some style issues

### CODE REVIEW

**Comment by vidartf** [comment]
Actually, most of this is style issues, with only a handful of real fixes :)

**Comment by to266** [comment]
I think I'm OK with the travis / appveyor / style fixes, and I trust that you got the ROI/widgets working correctly as well, but you definitely broke the FEI reader. Yours also does not pass the tests for me locally (while mine does, you might want to update)

**Comment by vidartf** [comment]
Still can't get Travis to run, might there be an encoding issue with `Release.py`? I'll leave the FEI issues to you, as this PR just contains which changes I did previously to get it to work, but this was a bit of trial and error.

**Comment by to266** [comment]
Sure. Now we actually have FEI files in the tests, so we could test it.

```python
ERROR: Failure: IndentationError (unexpected indent (Release.py, line 20))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/testenv/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/miniconda2/envs/testenv/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda2/envs/testenv/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda2/envs/testenv/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/miniconda2/envs/testenv/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/home/travis/miniconda2/envs/testenv/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/hyperspy/hyperspy/hyperspy/__init__.py", line 38, in <module>
    from . import Release
  File "/home/travis/build/hyperspy/hyperspy/hyperspy/Release.py", line 20
    name = 'hyperspy'
```
This is the error that travis complains about, however I can't understand / find what's wrong...

**Comment by vidartf** [comment]
I reverted the FEI chagnes, but added one fix for error here + expects warning.

**Pull request merged**
