### PR TITLE
Lazy improvements

### PR DESCRIPTION
**Pull request by francisco-dlp**
I have merged with the current Rnp and added a test. Unfortunately the test has highlighted a bug in the lazy version of `align_zero_loss_peak`. I have added a workaround (see 
43fd615) but it is not an ideal one because it makes the computation less lazy. Do you know what is the real issue?

### CODE REVIEW

**Comment by francisco-dlp** [comment]
The latest commit that fixes an ``estimate_zero_loss_peak`` bug highlight a new `_map_iterate` one, any idea of what's the issue?

**Comment by to266** [comment]
Sorry, `np.nan` not having `shape` unlike all other `np.float32`s was the issue. Fixed / worked around in https://github.com/to266/hyperspy/commit/d7d0ae473fa85962b59dad50d9e4b00987553ea7

**Comment by francisco-dlp** [comment]
Thanks. I've found the issue myself this morning and fixed it by using ``np.asarray`` inside of `_map_iterate` (sorry for not having pushed it earlier). Although this was only causing an issue with shift, I thought that this approach may protect us from a future return of the issue elsewhere. If you agree with this solution. I'll send a PR with the different solution after merging yours.

There is one test failing but the reason is unrelated to this so I'll fix it in a new one.

**Comment by francisco-dlp** [comment]
The PR is #1810

**Pull request merged**
